server:
  port: 9527
  servlet:
    context-path: /gateway-service

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由，利用微服务名进行路由
      routes:
        - id: payment-service-route
#          uri: http://localhost:8001
          uri: lb://PAYMENT-SERVICE
          predicates:
#            - Path=/payment-service/payment/hystrix/ok
            - Path=/payment-service/**

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    #false表示不向服务注册中心注册自己
    register-with-eureka: true
    #false表示自己就是服务注册中心，不需要去检索服务
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/
