server:
  port: 8083
  servlet:
    context-path: /order-service

spring:
  application:
    name: order-service
  cloud:
    nacos:
      discovery:
        server-addr: http://123.56.74.135:8848

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.cloud.entity



management:
  endpoints:
    web:
      exposure:
        include: '*'

