server:
  port: 2001
  servlet:
    context-path: /seata-order-service

spring:
  application:
    name: seata-order

  cloud:
    alibaba:
      seata:
        tx-service-group: fsp_tx_group
    nacos:
      discovery:
        server-addr: http://localhost:8848
#        server-addr: http://123.56.74.135:8818
    sentinel:
      transport:
        dashboard: http://localhost:8080
        port: 8719

  datasource:
    driver-class-name: org.gjt.mm.mysql.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://123.56.74.135:3306/seata_order?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    password: admin
    username: admin
    filters: stat
    initialSize: 2
    maxActive: 300
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: false
    maxPoolPreparedStatementPerConnectionSize: 200

ribbon:
  #建立连接超时时间
  ConnectTimeout: 5000
  #建立连接之后，读取响应资源超时时间
  ReadTimeout: 10000

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.cloud.entity

mybatis-plus:
  global-config:
    db-config:
      table-prefix: t_

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    com.example.cloud.**: debug

feign:
  sentinel:
    enabled: true