server:
  port: 777
  servlet:
    context-path: /oauth-resource

spring:
  application:
    name: oauth-resource
#  cloud:
#    nacos:
#      discovery:
#        server-addr: http://localhost:8848
  datasource:
    driver-class-name: org.gjt.mm.mysql.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://123.56.74.135:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    password: admin
    username: admin
    filters: stat
    initialSize: 2
    maxActive: 300
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: false
    maxPoolPreparedStatementPerConnectionSize: 200

#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.example.cloud.entity


management:
  endpoints:
    web:
      exposure:
        include: '*'
security:
  oauth2:
    resource:
      token-info-uri: http://182.61.42.98:666/oauth-server/oauth/check_token
#      token-info-uri: http://192.168.124.5:666/oauth-server/oauth/check_token
      prefer-token-info: true

    client:
      access-token-uri: http://182.61.42.98:666/oauth-server/oauth/token
#      access-token-uri: http://192.168.124.5:666/oauth-server/oauth/token
      user-authorization-uri: http://182.61.42.98:666/oauth-service/oauth/authorise
#      user-authorization-uri: http://192.168.124.5:666/oauth-service/oauth/authorise
      client-id: test_client
      client-secret: 123456
      grant-type: client_credentials

logging:
  level:
    org.springframework.security: debug